//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHorizon.ApplicationCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectHorizon.ApplicationCore.Properties.EmailResources", typeof(EmailResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AddedSubIcon {
            get {
                object obj = ResourceManager.GetObject("AddedSubIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ApprovalsIcon {
            get {
                object obj = ResourceManager.GetObject("ApprovalsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,600|Raleway:400,400italic,500,600,800,700,300,200);
        ///    span.preheader {display:none;height:0px;margin:0px;}
        ///    @media only screen and (max-width: 480px){
        ///     .device-width {width:90% !important;height:auto !important;min-width:380px !important;margin:0 auto !important;}
        ///     .device-width-inner {width:85% !important; height: auto !important;margin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ChangeEmailTemplate {
            get {
                return ResourceManager.GetString("ChangeEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,600|Raleway:400,400italic,500,600,800,700,300,200);
        ///
        ///        span.preheader {
        ///            display: none;
        ///            height: 0px;
        ///            margin: 0px;
        ///        }
        ///
        ///        @media only screen and (max-width: 480px) {
        ///            .device-width {
        ///                width: 90% !important;
        ///                height: auto !important;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DailyNotificationsTemplate {
            get {
                return ResourceManager.GetString("DailyNotificationsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FailedIcon {
            get {
                object obj = ResourceManager.GetObject("FailedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap NewAppIcon {
            get {
                object obj = ResourceManager.GetObject("NewAppIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,600|Raleway:400,400italic,500,600,800,700,300,200);
        ///
        ///        span.preheader {
        ///            display: none;
        ///            height: 0px;
        ///            margin: 0px;
        ///        }
        ///
        ///        @media only screen and (max-width: 480px) {
        ///            .device-width {
        ///                width: 90% !important;
        ///                height: auto !important;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewPasswordTemplate {
            get {
                return ResourceManager.GetString("NewPasswordTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,600|Raleway:400,400italic,500,600,800,700,300,200);
        ///
        ///        span.preheader {
        ///            display: none;
        ///            height: 0px;
        ///            margin: 0px;
        ///        }
        ///
        ///        @media only screen and (max-width: 480px) {
        ///            .device-width {
        ///                width: 90% !important;
        ///                height: auto !important;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewSubscriptionTemplate {
            get {
                return ResourceManager.GetString("NewSubscriptionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap NewVersionIcon {
            get {
                object obj = ResourceManager.GetObject("NewVersionIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PassResetIcon {
            get {
                object obj = ResourceManager.GetObject("PassResetIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,600|Raleway:400,400italic,500,600,800,700,300,200);
        ///    span.preheader {display:none;height:0px;margin:0px;}
        ///    @media only screen and (max-width: 480px){
        ///     .device-width {width:90% !important;height:auto !important;min-width:380px !important;margin:0 auto !important;}
        ///     .device-width-inner {width:85% !important; height: auto !important;margin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ShopRequestResponseTemplate {
            get {
                return ResourceManager.GetString("ShopRequestResponseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,600|Raleway:400,400italic,500,600,800,700,300,200);
        ///    span.preheader {display:none;height:0px;margin:0px;}
        ///    @media only screen and (max-width: 480px){
        ///     .device-width {width:90% !important;height:auto !important;min-width:380px !important;margin:0 auto !important;}
        ///     .device-width-inner {width:85% !important; height: auto !important;margin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ShopRequestTemplate {
            get {
                return ResourceManager.GetString("ShopRequestTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SubActivationIcon {
            get {
                object obj = ResourceManager.GetObject("SubActivationIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SubGetStartedIcon {
            get {
                object obj = ResourceManager.GetObject("SubGetStartedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,600|Raleway:400,400italic,500,600,800,700,300,200);
        ///    span.preheader {display:none;height:0px;margin:0px;}
        ///    @media only screen and (max-width: 480px){
        ///     .device-width {width:90% !important;height:auto !important;min-width:380px !important;margin:0 auto !important;}
        ///     .device-width-inner {width:85% !important; height: auto !important;margin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SubscriptionInviteTemplate {
            get {
                return ResourceManager.GetString("SubscriptionInviteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SuccessIcon {
            get {
                object obj = ResourceManager.GetObject("SuccessIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
